# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.Form = QtWidgets.QWidget(MainWindow)
        self.Form.setObjectName("Form")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, -1, 791, 551))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cursor_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.cursor_button.setIconSize(QtCore.QSize(32, 32))
        self.cursor_button.setCheckable(False)
        self.cursor_button.setObjectName("cursor_button")
        self.verticalLayout_2.addWidget(self.cursor_button)
        self.line_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.line_button.setIconSize(QtCore.QSize(32, 32))
        self.line_button.setObjectName("line_button")
        self.verticalLayout_2.addWidget(self.line_button)
        self.rect_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.rect_button.setIconSize(QtCore.QSize(32, 32))
        self.rect_button.setObjectName("rect_button")
        self.verticalLayout_2.addWidget(self.rect_button)
        self.polygon_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.polygon_button.setIconSize(QtCore.QSize(32, 32))
        self.polygon_button.setObjectName("polygon_button")
        self.verticalLayout_2.addWidget(self.polygon_button)
        self.ellipse_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.ellipse_button.setIconSize(QtCore.QSize(32, 32))
        self.ellipse_button.setObjectName("ellipse_button")
        self.verticalLayout_2.addWidget(self.ellipse_button)
        self.curve_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.curve_button.setIconSize(QtCore.QSize(32, 32))
        self.curve_button.setObjectName("curve_button")
        self.verticalLayout_2.addWidget(self.curve_button)
        self.select_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.select_button.setIconSize(QtCore.QSize(32, 32))
        self.select_button.setObjectName("select_button")
        self.verticalLayout_2.addWidget(self.select_button)
        self.move_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.move_button.setIconSize(QtCore.QSize(32, 32))
        self.move_button.setObjectName("move_button")
        self.verticalLayout_2.addWidget(self.move_button)
        self.scale_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.scale_button.setIconSize(QtCore.QSize(32, 32))
        self.scale_button.setObjectName("scale_button")
        self.verticalLayout_2.addWidget(self.scale_button)
        self.rotate_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.rotate_button.setIconSize(QtCore.QSize(32, 32))
        self.rotate_button.setObjectName("rotate_button")
        self.verticalLayout_2.addWidget(self.rotate_button)
        self.clip_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.clip_button.setIconSize(QtCore.QSize(32, 32))
        self.clip_button.setObjectName("clip_button")
        self.verticalLayout_2.addWidget(self.clip_button)
        self.color_button = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.color_button.setIconSize(QtCore.QSize(32, 32))
        self.color_button.setObjectName("color_button")
        self.verticalLayout_2.addWidget(self.color_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.Form)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMouseTracking(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cursor_button.setToolTip(_translate("MainWindow", "光标模式"))
        self.cursor_button.setText(_translate("MainWindow", "..."))
        self.line_button.setToolTip(_translate("MainWindow", "线段"))
        self.line_button.setText(_translate("MainWindow", "..."))
        self.rect_button.setToolTip(_translate("MainWindow", "矩形"))
        self.rect_button.setText(_translate("MainWindow", "..."))
        self.polygon_button.setToolTip(_translate("MainWindow", "多边形"))
        self.polygon_button.setText(_translate("MainWindow", "..."))
        self.ellipse_button.setToolTip(_translate("MainWindow", "椭圆"))
        self.ellipse_button.setText(_translate("MainWindow", "..."))
        self.curve_button.setToolTip(_translate("MainWindow", "曲线"))
        self.curve_button.setText(_translate("MainWindow", "..."))
        self.select_button.setToolTip(_translate("MainWindow", "选择图元"))
        self.select_button.setText(_translate("MainWindow", "..."))
        self.move_button.setToolTip(_translate("MainWindow", "平移图元"))
        self.move_button.setText(_translate("MainWindow", "..."))
        self.scale_button.setToolTip(_translate("MainWindow", "缩放图元"))
        self.scale_button.setText(_translate("MainWindow", "..."))
        self.rotate_button.setToolTip(_translate("MainWindow", "旋转图元"))
        self.rotate_button.setText(_translate("MainWindow", "..."))
        self.clip_button.setToolTip(_translate("MainWindow", "裁剪线段"))
        self.clip_button.setText(_translate("MainWindow", "..."))
        self.color_button.setToolTip(_translate("MainWindow", "调色板"))
        self.color_button.setText(_translate("MainWindow", "..."))
